CREATE DATABASE QL_BCVT1
GO
USE QL_BCVT1


CREATE TABLE CHINHANH
(
   BRANCH_CODE NVARCHAR(5) PRIMARY KEY,
   BRANCH_ADDRESS NVARCHAR(200) NOT NULL,
   BRANCH_PHONE INT
)

CREATE TABLE KHACHHANG
(
   CUS_CODE NVARCHAR(5) PRIMARY KEY,
   CUS_NAME NVARCHAR(250),
   CUS_BIRTH DATETIME,
   CUS_PHONE INT,
   CUS_ADDRESS NVARCHAR(250) NOT NULL,
   BRANCH_CODE NVARCHAR(5) FOREIGN KEY REFERENCES CHINHANH(BRANCH_CODE),
   CUS_STATUS NVARCHAR(50)
)


CREATE TABLE SODUKH
(
   CUS_CODE NVARCHAR(5) REFERENCES KHACHHANG(CUS_CODE),
   PRIMARY KEY(CUS_CODE),
   SD_ACCOUNTBALANCE FLOAT NOT NULL
)

CREATE TABLE HOATDONG
(
   CUS_CODE NVARCHAR(5) REFERENCES KHACHHANG(CUS_CODE),
   PRIMARY KEY(CUS_CODE),
   HOATDONG_DAY DATETIME,
   HOATDONG_DESC NVARCHAR(255) NOT NULL,
   --nghe/ g?i/ n?p ti?n
   HOATDONG_PRICE FLOAT
   --GIÁ C?, N?U LÀ TR? THÌ CÓ TR? TR??C CÒN N?P THÌ ?? S? BTH
)

CREATE TABLE NHANVIEN
(
    STAFF_CODE NVARCHAR(5) PRIMARY KEY,
	STAFF_NAME NVARCHAR(250) NOT NULL,
	STAFF_PHONE NVARCHAR(11) NOT NULL,
	STAFF_ADDRESS NVARCHAR(255),
	BRANCH_CODE NVARCHAR(5) FOREIGN KEY REFERENCES CHINHANH(BRANCH_CODE)
)

CREATE TABLE DICHVU
(
     SERVICE_CODE NVARCHAR(5) PRIMARY KEY,
	 SERVICE_NAMES NVARCHAR(250) NOT NULL,
	 SERVICE_PRICE INT NOT NULL,
	 SERVICE_DURATION NVARCHAR(15),  -- TH?I H?N
	 SERVICE_DESC NVARCHAR(255),
	 SERVICE_TYPE NVARCHAR(50)
)
-- Hop dong only for afterpaid
-- Done
CREATE TABLE HOPDONG
(
     CONTRACT_CODE NVARCHAR(5) PRIMARY KEY,
	 CUS_CODE NVARCHAR(5) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
	 SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE),
	 CONTRACT_STATUS NVARCHAR(100)
)
-- Done
CREATE TABLE CTDK
(
     REG_CODE NVARCHAR(5) PRIMARY KEY,
	 CONTRACT_CODE NVARCHAR(5) FOREIGN KEY  REFERENCES HOPDONG(CONTRACT_CODE),
	 REG_END DATETIME NOT NULL,
	 REG_PAYMENT NVARCHAR(20) NOT NULL
)

CREATE TABLE HOADON
(
     INV_CODE NVARCHAR(5) PRIMARY KEY,
	 STAFF_CODE NVARCHAR(5) FOREIGN KEY REFERENCES NHANVIEN(STAFF_CODE),
	 CUS_CODE NVARCHAR(5) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
	 INV_DAY DATETIME, -- ngày thu tiền
	 INV_TOTAL INT
)

CREATE TABLE CTHD
(
     LINE_CODE NVARCHAR(5) PRIMARY KEY,
	 INV_CODE NVARCHAR(5) FOREIGN KEY REFERENCES HOADON(INV_CODE),
	 SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE),
)
-- Done
CREATE TABLE LOAILOI
(
     TE_CODE NVARCHAR(2) PRIMARY KEY,
	 SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE),
)

-- Done
CREATE TABLE LOI
(
      ERROR_CODE NVARCHAR(6) PRIMARY KEY,
	  TE_CODE NVARCHAR(2) FOREIGN KEY REFERENCES LOAILOI(TE_CODE),
	  CUS_CODE NVARCHAR(5) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
	  ERROR_DESC NVARCHAR(255) NOT NULL
)
-- Done
CREATE TABLE COMMENT
(
      COMMENT_CODE NVARCHAR(5) PRIMARY KEY,
      CUS_CODE NVARCHAR(5) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
      COMMENT_DESC NVARCHAR(255),
	  COMMENT_STAR INT NOT NULL,
	  SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE)

)

