--ngày xxxx khách hàng A có đăng kí dịch vụ gì
--Khách A đang sử dụng dịch vụ gì
SELECT DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME
FROM KHACHHANG JOIN HOPDONG ON KHACHHANG.CUS_CODE= HOPDONG.CUS_CODE
JOIN DICHVU ON HOPDONG.SERVICE_CODE = DICHVU.SERVICE_CODE
WHERE KHACHHANG.CUS_NAME= N'BÙI ĐỨC TIẾN' AND HOPDONG.CONTRACT_STATUS = 'Active'

--xem tổng doanh thu hàng tháng, bằng cách tính tổng số thu 3 đợt của khách trả sau, của khách trả trước, và khách đăng kí gói wifi trong tháng đó
-- tổng doanh thu trả trước
SELECT MONTH(HOATDONG_DAY) AS MONTH, SUM(HOATDONG_PRICE) AS DOANHTHU
FROM HOATDONG
WHERE HOATDONG_PRICE>0 AND YEAR(HOATDONG_DAY) = 2021
GROUP BY MONTH(HOATDONG_DAY)

-- tổng doanh thu trả sau
SELECT MONTH(INV_DAY) AS MONTH, SUM(INV_TOTAL) AS DOANHTHU
FROM HOADON
WHERE YEAR(INV_DAY)=2021
GROUP BY MONTH(INV_DAY)

--xem dịch vụ nào được đăng kí nhiều nhất bằng cách join các bảng hoa don và ct dang ki, group by dịch vụ rồi tính tổng
SELECT TOP(5) DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME, COUNT(CTDK.REG_CODE) AS TIMES
FROM DICHVU FULL JOIN HOPDONG ON DICHVU.SERVICE_CODE= HOPDONG.SERVICE_CODE
FULL JOIN CTDK ON HOPDONG.CONTRACT_CODE = CTDK.CONTRACT_CODE
GROUP BY DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME
ORDER BY COUNT(CTDK.REG_CODE) DESC


--xem khu vực hay chi nhánh nào có nhiều khách hàng để có thể thêm/ bớt nhân viên và từ đó có thể chăm sóc khách hàng tốt hơn
SELECT KHACHHANG.BRANCH_CODE, COUNT(CUS_CODE) AS NUMBER
FROM KHACHHANG
GROUP BY BRANCH_CODE
HAVING COUNT(CUS_CODE) > 8
ORDER BY COUNT(CUS_CODE) DESC

--xem phản hồi khách hàng về một dịch vụ dựa trên số sao trung bình mà khách hàng đánh giá một dịch vụ
SELECT COMMENT_STAR, COMMENT_DESC
FROM COMMENT
WHERE COMMENT_STAR >=3
ORDER BY COMMENT_STAR DESC

--check xem có khách hàng nào có sinh nhật trong tháng
SELECT CUS_CODE, CUS_NAME, CUS_BIRTH 
FROM KHACHHANG
WHERE MONTH(CUS_BIRTH) = 6

--Check xem khách hàng này được thu ngân nào thu tiền và thu bao nhiêu
SELECT NHANVIEN.STAFF_CODE, INV_TOTAL
FROM HOADON JOIN NHANVIEN ON HOADON.STAFF_CODE = NHANVIEN.STAFF_CODE
JOIN KHACHHANG ON HOADON.CUS_CODE = KHACHHANG.CUS_CODE
WHERE KHACHHANG.CUS_NAME = N'PHAN THỊ KHÁNH LINH'


--Khách hàng nào đã sử dụng hết tất cả các dịch vụ SMS
SELECT KHACHHANG.CUS_CODE, CUS_NAME, CUS_PHONE
FROM KHACHHANG FULL JOIN HOPDONG ON KHACHHANG.CUS_CODE = HOPDONG.CUS_CODE
FULL JOIN DICHVU ON HOPDONG.SERVICE_CODE = DICHVU.SERVICE_CODE
WHERE SERVICE_DESCRIPTION_NAME LIKE 'SMS'


-- khách hàng cmt nhieu nhat
SELECT TOP(1) KHACHHANG.CUS_CODE, CUS_NAME, COUNT(COMMENT_CODE) AS TIMES
FROM KHACHHANG JOIN COMMENT ON KHACHHANG.CUS_CODE = COMMENT.CUS_CODE
GROUP BY KHACHHANG.CUS_CODE, CUS_NAME
ORDER BY COUNT(COMMENT_CODE) DESC

-- dịch vụ nào có số lần khách hàng đăng ký ít nhất và số lần đky
SELECT TOP(5) DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME, COUNT(CTDK.REG_CODE) AS TIMES
FROM DICHVU JOIN HOPDONG ON DICHVU.SERVICE_CODE = HOPDONG.SERVICE_CODE
JOIN CTDK ON HOPDONG.CONTRACT_CODE = CTDK.CONTRACT_CODE
GROUP BY DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME
ORDER BY COUNT(CTDK.REG_CODE)

--Khách hàng nào gọi hết nhiều tiền nhất và tổng số 
SELECT KHACHHANG.CUS_CODE, CUS_NAME, CUS_PHONE, SUM(HOATDONG_PRICE) AS TOTAL
FROM KHACHHANG JOIN HOATDONG ON KHACHHANG.CUS_CODE = HOATDONG.CUS_CODE
WHERE HOATDONG_DESC = 'GỌI'
GROUP BY KHACHHANG.CUS_CODE, CUS_NAME, CUS_PHONE
ORDER BY SUM(HOATDONG_PRICE) DESC

